### ISSUE TITLE
Add X,Y,Z and DISTANCE attributes to FINDITEMs (DISTANCE only for those on the ground)

### ISSUE THREAD

**Issue by moinphyst** [Lady-Binary/EasyLOU#100]
As of right now, using FindItem("Cotton Plant") will give you a great list of all cotton plants nearby. Unfortunately, they don't seem to be in order by distance like other Find functions - probably because it was intended to be used for searching in container primarily. This makes for a seemingly random (maybe numerically by id) and inefficient path when harvesting cotton or regs.

If possible, I would like a FINDITEM[id].dist added, though I understand it would not be very useful for items in container. Perhaps this could only be added if the item is not in a container?

I would add picking cotton and regs to my lumberjack script if I could ensure that I wasn't running a long ways away for them.

**Comment by Lady-Binary** [comment]
I've added X,Y, and Z coordinates, and also the distance.

X Y and Z coordinates are funny when the item is within a container, so calculating the distance doesn't make much sense.
I have calculated the distance only for those items on the floor, and I think I also sorted by it.
