### ISSUE TITLE
LogOff command

### ISSUE THREAD

**Issue by nerdhere** [Lady-Binary/EasyLOU#108]
Wondering if possible to create a built-in LogOff() function to log off character. I would use it when out of materials so my character isn't sitting idle in game.

Example:
FindItem("Black Pearl", BACKPACKID)
if FINDITEMID == nil then
     LogOff
end

**Comment by Lady-Binary** [comment]
yep, good idea, it should be possible ... I'll have a look at it! thanks for the feedback!
