### ISSUE TITLE
Fix issue with disappearing vertical scrollbar

### ISSUE THREAD

**Issue by Factorial-Prime** [Lady-Binary/EasyLoU#149]
**Is your feature request related to a problem? Please describe.**
When editing long scripts there aren't vertical scroll bars in the editor

**Describe the solution you'd like**
Add vertical scroll bars to the editor

**Describe alternatives you've considered**
None that I can think of

**Additional context**
None

**Comment by Factorial-Prime** [comment]
I'll take a stab at implementing this and open a PR

**Comment by Factorial-Prime** [comment]
Hmm I noticed when I built the solution and ran it in debug via visual studios the vertical scroll bars are there. Maybe it's something with the latest release?

**Comment by Lady-Binary** [comment]
I've found at least one case where the scrollbar was disappearing.

I think I've fixed it now, but I also made the scrollbar always visible: I don't think there's any harm in always having them.

Will be fixed with next release.
