### ISSUE TITLE
.csproj files not existent in the repos

### ISSUE THREAD

**Issue by your-e-mom** [Lady-Binary/EasyLoU#181]
could you attach them because my pc cant build it and ci is complaining

**Comment by Lady-Binary** [comment]
hi @your-e-mom ,

can you please clarify what you mean with "ci is complaining"? I don't see any build failing.

which .csproj are you talking about exactly?

The main project, EasyLoU, has its .csproj in the EasyLoU folder, while each other submodule has its own .csproj.

I wonder if you forgot to pull the submodules?

```
git@github.com:Lady-Binary/EasyLoU.git
git submodule init 
git submodule update
```

And once you've done that, just open the .sln file and it should build out of the box.
