### ISSUE TITLE
HUNGER variable

### ISSUE THREAD

**Issue by thiagomaf** [Lady-Binary/EasyLOU#41]
Just wondering whether we can have a HUNGER variable.
I am not sure how the hunger status is stored, but it would be interesting to at least have the indication if it is "Full" or not - e.g. from the paperdoll.

Is it possible?

**Comment by Lady-Binary** [comment]
hi @thiagomaf , this is solved.

can you please check the example https://github.com/Lady-Binary/EasyLOU/blob/master/Examples/08-hunger.lua and see if it works as expected?

Thanks!
