### ISSUE TITLE
Improve FIND variables, they should be arrays/tables so that it's much easier to use them

### ISSUE THREAD

**Issue by Lady-Binary** [Lady-Binary/EasyLOU#52]
**Is your feature request related to a problem? Please describe.**
Including utils.lua just for the ExtractFirstId() is too much. 

**Describe the solution you'd like**
ExtractFirstId() should be a core function, so that users are not required to include utils.lua every time.
In alternative, FINDITEMID, FINDITEMNAME etc could be tables, so that users can query them directly with [0] [1] etc ???

**Comment by thiagomaf** [comment]
I have been using a getElement(vec, index) function. Could include something to get last if index == -1
Idk, have the impression is more generic. Should perhaps also include an argument for the separator (i.e. ",").

Would it be even easier solution have an optional argument in the e.g. FindItem() command to indicate the index?

Besides that, I guess there will be regexps that will directly return the first or the last element of the string - i.e. avoid entering the for loop and subsequent break.

**Comment by Lady-Binary** [comment]
So, I came up with this solution.

All the "FIND" variables wil be stable starting with release 1.0.0.29.

There is no need for the ExtractFirstId() method anymore, and you will be able to use them as follows:

```
FindItem("book")

print("Total items found: " .. #FINDITEMID)

print("First item: " .. FINDITEMID[1])

print("Last item: " .. FINDITEMID[#FINDITEMID])

print("Items list:")
for v in FINDITEMID do
  print(v)
end
```

How does it sound?

**Comment by thiagomaf** [comment]
This is a great solution, much simpler than what we previously mentioned. 
I understand it will break lots of stuff, but better now than later.... this will simplify lots of stuff.
