### ISSUE TITLE
New clear() command to clear EasyLOU output log

### ISSUE THREAD

**Issue by Lady-Binary** [Lady-Binary/EasyLOU#68]

**Comment by thiagomaf** [comment]
Perhaps also a command to concatenate to the current content of the output log without breaking the line \n.
The print() function will always print to the next line.... a cat() like function to print the current row would be interesting.

**Comment by Lady-Binary** [comment]
@thiagomaf so, you mean a print() function that doesn't append the newline? I don't want to break existing scripts again, so maybe I'll add a write() function that doesn't break the line. how does it sound?

**Comment by thiagomaf** [comment]
Yeah, that is what I mean - keep print() as it is and add a new function e.g. write() as you suggest.

**Comment by Lady-Binary** [comment]
ok, write() command will be implemented with #74
