### ISSUE TITLE
Add X,Y,Z attributes to FINDPERMANENTs. Add ability to use Move() with PERMANENTID.

### ISSUE THREAD

**Issue by nerdhere** [Lady-Binary/EasyLOU#90]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
FindPermanent ability to provide x,y,z coordinates for the found objects
Example: Use FindPermanent("tree") and somehow pull the tree X,Y,Z coordinates to use with MoveEx

**Comment by Lady-Binary** [comment]
had a quick look and should be feasible.... should be in the next release! :)

**Comment by Lady-Binary** [comment]
@nerdhere actually, may I ask you why you need x y z? you want to move over there? it should be feasible by just passing the ID of the permanent object to the Move function ... is that not working ?

**Comment by moinphyst** [comment]
@Lady-Binary I can confirm that this was not working in 1.0.0.32. Have not tried since r33.

**Comment by thiagomaf** [comment]
This would be convenient for Mobiles.

**Comment by Lady-Binary** [comment]
> @Lady-Binary I can confirm that this was not working in 1.0.0.32. Have not tried since r33.

@moinphyst are you saying that you tried passing the ID to the Move() function and it didn't work?

@thiagomaf same for mobiles ... Move(MOBILEID) should move to the mobile ... have you tried?

I'll give it a try, maybe Move it's bugged

**Comment by moinphyst** [comment]
@Lady-Binary Move(id) works just fine for mobiles, it did not work for permanents.

**Comment by Lady-Binary** [comment]
I'll investigate then, thank you!

just want to confirm with the original poster @nerdhere - can you confirm that you needed x,y,z only because you wanted to move to the rock, and not for another reason that I'm missing?

I'd rather fix Move(ID) so that it works, rather than adding new vars.

**Comment by thiagomaf** [comment]
It would be convenient to have the mobile's X, Y, Z position so one can move to an offset position - e.g. keep X distance from the mob.

**Comment by Lady-Binary** [comment]
gotcha, now I understand why.

**Comment by Lady-Binary** [comment]
created issue #99 for mobiles

**Comment by Lady-Binary** [comment]
turns out, permanent objects are not regular gameobjects. they do not have a gameobject ID that can be used with Move() and other functions, but they have a PERMANENTID instead.

in order to avoid confusion going forward, i will rename this ID for what it really is, a PERMANENTID.

also, I will add X Y and Z to the FINDPERMANENT results.

**Comment by Lady-Binary** [comment]
It's now also possible to use Move() with the PERMANENTID :) I think I've fixed it.
