### ISSUE TITLE
FindItem not clearing previously found objects/table(s) no longer on screen or in pack

### ISSUE THREAD

**Issue by nerdhere** [Lady-Binary/EasyLOU#93]
**Describe the bug**
FindItem not clearing previously found objects/table(s) which are no longer on screen or in pack.

For example: Use FindItem("pickaxe") when bank window open and backpack open. Assuming there are pickaxes in both bank box and backpack, it will list all pickaxes in FINDITEMID table. 

Problem: When, say, the bank box is no longer open/visible (I'm in a forest or mine) and FindItem("pickaxe") is ran again, it still lists all of the pickaxes from the bank box instead of just the pickaxes in the backpack (aka not clearing FindItem table upon new FindItem search?). This causes Equip("pickaxe") to malfunction and unable to equip pickaxe in backpack although it is there.

**To Reproduce**
I have a getPickaxe() function which opens bank and finds "Harvesting" toggled bag where pickaxes are stored. This produces ~20 FINDITEMIDs initially. It pulls 2 into my backpack. Later, upon doMine() call [same as doTree but for mining], Equip("pickaxe") is attempted which should pull from backpack as its the only container around/open. However, it gets confused since there are still many FINDITEMIDs listed from previous bank container in the table. It did not clear table on the most recent FindItem command.

**Portion of script that may help reproduce:**
function getPickAxe()
sleep(1000)
Say("bank")
sleep(6000)
FindItem("Harvesting")
if FINDITEMID != "N/A" then
	sleep(600)
	ContextMenu(FINDITEMID[1], "Open")
	sleep(5000)
	FindItem(" exceptional pickaxe")
	pickAxeBag = FINDITEMCNTID[1]
	
else
	print("No harvesting bag in bank with pickaxes.")
end

local count = 0
repeat
	FindItem(" exceptional pickaxe", pickAxeBag)
	if FINDITEMID[1] == "N/A" or FINDITEMID[1] == "N/A" then
		print('bank is out of packaxes...')
		sleep(10000)
	else
		sleep(600)
		Drag(tonumber(FINDITEMID[1]))
		sleep(800)
		Dropc(BACKPACKID)
		sleep(800)
		count = count + 1
	end
until count == 2
end

function Equip(item) -- stole this from utils.lua
    FindItem(item)
	local tool_id = (FINDITEMID[1])
	local cont_id = (FINDITEMCNTID[1])
	if tool_id == nil or tool_id == "N/A" then
		print(item .. " not found!")
		if start_getPickaxe == true then
			getPickAxe()
			start_getPickaxe = false
			return
		else
			print("Recalling to bank...")
			getBankPickaxe = true
			dropOre = true
			recallYewBank()
			return
		end
	end
	if tostring(cont_id) == tostring(CHARID) then
		print(item .. " already equipped!")
		return	
	end
	print("Equipping " .. item)
	ContextMenu(tool_id, " Equip")
end

start_getPickaxe = true
Equip("  exceptional pickaxe")

**Expected behavior**
FindItem/FINDITEMID table(s) should clear upon every new FindItem call - maybe?
. 

**Screenshots**

**Desktop (please complete the following information):**
 - EasyLOU Version: 1.0.0.32
 - Client Version: 1.1.0.0
 - OS: Windows 10

**Additional context**
Willing to show on screen share if needed

**Comment by Lady-Binary** [comment]
For now, I'd suggest you call FindItem("Pickaxe",BACKPACKID") when you are in the mine/wood, or any other ID of an object container where you put all your axes.

It looks like the Client is keeping all those objects in memory, and I still could not find a good workaround for this.

I'll keep investigating, but please have a look if the workaround works for you!

**Comment by nerdhere** [comment]
thanks! working

**Comment by Lady-Binary** [comment]
cool! I'll leave this open, I will try to investigate a little bit if there's some workaround in the future.

**Comment by Lady-Binary** [comment]
I think this should be fixed with the next release.

Can you please verify @nerdhere ?
